--- 
commands: 
  - "ffmpeg -f v4l2 -framerate 25 -video_size 640x480 -i /dev/video1 -f mpegts -codec:v mpeg1video -s 640x480 -b:v 1000k -bf 0 ${video0}"

http:
  port: 8087
  waitMS: 500
  timeoutMS: 1000

log: ./vw.log

bufferSize: 1024000

mux:
  workers: 3
  bufferLength: 12

clients: 
  bufferLength: 3

variables:
  uuid: 49270598-9da2-4209-98da-e559f0c587b4
  session: 7525cb39-554e-43e1-90ed-3a97e8d1c6bf
  outurl: "ws://localhost:8080"

streams: 
  -   destination: "${outurl}/in/video1"
      feeds: 
        - video0

